### ISSUE TITLE
lua error

### ISSUE THREAD

**Issue by T3rdW** [alexqu0822/alaChat#1]
Message: [ADDON_ACTION_BLOCKED] AddOn 'alaChat_Classic' tried to call the protected function '__SendChatMessage_hyperLinkEnhanced()'.
Time: Sun Jun 28 19:14:13 2020
Count: 1
Stack: [ADDON_ACTION_BLOCKED] AddOn 'alaChat_Classic' tried to call the protected function '__SendChatMessage_hyperLinkEnhanced()'.
Interface\AddOns\alaChat_Classic\chatEmote.lua:397: in function <Interface\AddOns\alaChat_Classic\chatEmote.lua:397>
[C]: ?
[C]: in function `pcall'
Interface\AddOns\MeetingHorn\Core\LFG.lua:246: in function <Interface\AddOns\MeetingHorn\Core\LFG.lua:240>
(tail call): ?
Interface\SharedXML\C_TimerAugment.lua:16: in function <Interface\SharedXML\C_TimerAugment.lua:14>

Locals: <none>

**Comment by alexqu0822** [comment]
I didnot notice issues on github before. It should be fixed by now.
