### ISSUE TITLE
LUA Error - Since latest update

### ISSUE THREAD

**Issue by mythrasus** [alexqu0822/alaChat#2]
Hi, getting the following LUA error since updating to latest 205r.210714

Message: Interface\AddOns\alaChat\module\channeltab.lua:659: attempt to index field '?' (a nil value)
Time: Fri Jul 16 09:27:51 2021
Count: 8
Stack: Interface\AddOns\alaChat\module\channeltab.lua:659: attempt to index field '?' (a nil value)

Locals:

**Comment by alexqu0822** [comment]
I didnot notice issues on github before. It should be fixed by now.
